### Vaughn's Master Alias list ###

### Program overrides
alias ll="ls -larht --color"
alias ls="ls --color"
alias fgrep="fgrep -i $*"
alias diff="colordiff --exclude=".svn" --exclude="*.pyc" $*"
alias df='df -ah'
alias less='less -r'  # Will correctly interpret color sequences.
 
### Handy shortcuts

# Recursive diff, without svn
alias rdiff='diff -r --exclude=\*\.svn $*'

# List only directories
alias lsd="ls -d */"

# 'lsr' - Easy recursive search
# Thank you, http://www.unix.com/unix-advanced-expert-users/69618-shell-programming-aliasing-set-f.html !
# The problem was that making lsr a shell script was causing the parameter to expand globs like *.css, which futzed find.
alias lsr='set -f; mylsr'
mylsr () {
  find  -L . -iname $@ |fgrep -v .svn
  set +f
}




### Edit/reload shortcuts
alias realias="source ~/.bash_aliases"
alias edalias="sublime ~/.bash_aliases"
alias edackrc="sublime ~/.ackrc"

alias s='sublime $1'
alias edhosts="sublime /etc/hosts"
alias edprofile="sublime ~/.bash_profile"
alias reprofile="source ~/.bash_profile"

alias pyserv="python -m SimpleHTTPServer"

alias irb='pry'

### Open OSX apps from the command line
alias calc="open -a calculator"
alias adium="open -a adium"
alias chrome='open -a "Google Chrome.app"'
alias firefox="open -a firefox"
alias 1p="open -a 1password"
alias xee="open -a xee"
alias jason="open -a jason"
alias mou="open -a Mou.app"
alias sqlpro="open -a Sequel\ Pro.app"


alias t=tab

tab () {
  # Will cd into current dir if called without arg.
  osascript -e 'tell application "Terminal"' \
            -e 'tell application "System Events" to keystroke "t" using {command down}' \
            -e "do script \"cd `pwd` && cd ${1-.} && clear\" in front window" \
            -e 'end tell' > /dev/null
}





